APP_PATH ||= '.'
RACK_ENV ||= 'development'

require 'hot_potato/core'
require 'hot_potato/cache'
require 'hot_potato/dsl'
require 'hot_potato/admin'
require 'hot_potato/app_task'
require 'hot_potato/app_task_info'
require 'hot_potato/app_task_server'
require 'hot_potato/supervisor_server'
require 'hot_potato/supervisor_info'
require 'hot_potato/queue_logger'
require 'hot_potato/faucet'
require 'hot_potato/worker'
require 'hot_potato/sink'
require 'hot_potato/utils'
require 'hot_potato/generate'
require 'hot_potato/generate_app_task'
require 'hot_potato/version'
